version: "3.2"

services:

  service_name:

    image: node_server_image

    container_name: node_server_container

    build:

      context: .

      dockerfile: "Dockerfile"

    ports:

      - "8000:8000"

    env_file:

     - .env